name: products_app
repository: https://github.com/teoboetti/products_app

ide:
  intellij:
    enabled: false

packages:
  - app
  - packages/**

command:
  version:
    # Only allow versioning to happen on master branch.
    branch: master
    # Generates a link to a prefilled GitHub release creation page.
    releaseUrl: true
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true

  bootstrap:
    environment:
      sdk: ">=3.3.0 <4.0.0"
      flutter: ">=3.19.2"

    dev_dependencies:
      build_runner: ^2.4.9
      mocktail: ^1.0.3

scripts:
  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks.

  analyze:
    # We are setting the concurrency to 1 because a higher concurrency can crash
    # the analysis server on low performance machines (like GitHub Actions).
    run: |
      melos exec -c 1 -- \
        dart analyze . --fatal-infos
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  format:
    run: |
      dart pub global run flutter_plugin_tools format && \
      swiftformat .
    description: |
      Formats the code of all packages (Java, Objective-C, and Dart).
       - Requires `flutter_plugin_tools` (`pub global activate flutter_plugin_tools`).
       - Requires `git`.
       - Requires `clang-format` (can be installed via Brew on MacOS).
       - Requires `swiftformat` (can be installed via Brew on macOS).
  
  test:select:
    run: melos exec -c 1 -- flutter test
    packageFilters:
      dirExists: test
    description: Run `flutter test` for selected packages.

  test:all:
    run: melos run test:select --no-select
    description: Run all Flutter tests in this project.

  coverage:
    run: |
      melos exec -- rm -rf coverage
      melos exec -- flutter test --coverage
      melos exec -- lcov --remove coverage/lcov.info '*.g.dart' -o coverage/lcov.info
      melos exec -- genhtml coverage/lcov.info --output-directory=coverage/html
      melos exec -- open coverage/html/index.html
    packageFilters:
      dirExists: test
    description: Generate coverage for the selected package.

  generate:
    exec: |
      dart run build_runner build --delete-conflicting-outputs
    description: |
      Generate .g.dart files if the package for selected packages.
    packageFilters:
      dependsOn: build_runner