name: products_app
description: Products App
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  api: ^0.1.0
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.2+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.8
  go_router: ^13.2.2
  google_fonts: ^6.2.1
  injectable: ^2.4.1
  intl: ^0.18.1
  sliver_tools: ^0.2.12
  url_launcher: ^6.2.5

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.4.1
  injectable_generator: ^2.6.1
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
