name: cicd

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

env:
  FLUTTER_MIN_VERSION: "3.19.0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v3
      - run: melos generate:all
      - run: melos test:all
